rm MatrixMethodGeneral_DATA_EMu
rm MatrixMethod_DATA_E
rm MatrixMethod_DATA_Mu
rm MatrixMethodGeneral_MC
rm MatrixMethod_MC
rm MatrixMethod_Efficiency_DATA_Estimation_E
rm MatrixMethod_Efficiency_DATA_Estimation_Mu
rm MatrixMethod_Efficiency_MC_Estimation_E
rm MatrixMethod_Efficiency_MC_Estimation_Mu

rm MatrixMethodGeneral_FastAnalysis_DATA_EMu
rm MatrixMethod_FastAnalysis_DATA_E
rm MatrixMethod_FastAnalysis_DATA_Mu
rm MatrixMethodGeneral_FastAnalysis_MC
rm MatrixMethod_FastAnalysis_MC

rm MatrixMethod_MC_NoWeight
rm MatrixMethodGeneral_FastAnalysis_MC_PullTest
rm MatrixMethod_FastAnalysis_MC_PullTest
rm MatrixMethod_FastAnalysis_MC_EpsilonsTest

rm MatrixMethod_Contamination_Studies

rm *.pdf
rm MatrixMethod*.root
rm *_log

